/*
 * Automatically generated file. DO NOT EDIT.
 * Espressif IoT Development Framework (ESP-IDF) Configuration Header
 */
#pragma once
#define CONFIG_CTRL_TRANSFER_DATA_MAX_BYTES 1024
#define CONFIG_SAMPLE_PROC_TASK_STACK_SIZE 3072
#define CONFIG_SAMPLE_PROC_TASK_PRIORITY 2
#define CONFIG_SAMPLE_PROC_TASK_CORE 0
#define CONFIG_USB_WAITING_AFTER_CONN_MS 50
#define CONFIG_USB_PROC_TASK_STACK_SIZE 3072
#define CONFIG_USB_PROC_TASK_PRIORITY 5
#define CONFIG_USB_PROC_TASK_CORE 1
#define CONFIG_NUM_BULK_STREAM_URBS 2
#define CONFIG_NUM_BULK_BYTES_PER_URB 2048
#define CONFIG_NUM_ISOC_STREAM_URBS 3
#define CONFIG_NUM_PACKETS_PER_URB_URB 4
